# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbb92c052a71bfa9103a67bd6a93407c978cba04e1a29a7c6668ad841914e3d7d5e12f538d83a8d6427024c820de7ccebc8d302c0a8777d136603a0b5437c9fe

test:
  secret_key_base: aa51ee42e5797cd7e62364ea844f6c4d44a646efa8695882cfcbfd430b92f341f53960aa8c78b571035b766e2778a9d4bb6fc2a4b2e9fde66c4d60bb436a081c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
